### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Review by TylerLeonhardt — APPROVED** [review]
LGTM :) thanks for doing this!

**Comment by gamebox** [comment]
Is there any way you could cut a new release including these changes?

**Comment by TylerLeonhardt** [comment]
Can do! I'm on vacation right now, but I'll do a new release by the end of next week.

**Comment by gamebox** [comment]
Oh, that's awesome!  The old version of request had a ton of
vulnerabilities, so much appreciated.  Enjoy the vacation!

**Comment by TylerLeonhardt** [comment]
This should be published now! Let me know if you have any trouble.

**Pull request merged**
